# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(max_length=100)),
                ('page_type', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, max_length=200, null=True)),
                ('next_content_short_title', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_content_short_title', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(blank=True, max_length=10, null=True)),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionTitle', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('html_content', models.TextField()),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
