# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subSectionTitle', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('html_content', models.TextField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Section'),
        ),
    ]
