# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_answered',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 5, 47, 9, 992532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_submitted',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 5, 47, 9, 992420, tzinfo=utc)),
        ),
    ]
